spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/DDoBii?serverTimezone=UTC&characterEncoding=UTF-8
    username: ijeong0416
    password: 340834

  # datasource:
    # url: ${DB_URL}
    # username: ${DB_ID}
    # password: ${DB_PW}

  # security:
  #   jwt:
  #     header: Authorization
  #     secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  #     token-validity-in-seconds: 604800
  security:
    jwt:
      secret: yourSecretKeyHere


  jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
          default_batch_fetch_size: 100
          format_sql: false
      open-in-view: false

  config:
    import: optional:file:.env[.properties]