# application.yml

spring:
  config:
    import: optional:file:.env.properties

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/DDoBii?serverTimezone=UTC&characterEncoding=UTF-8
    username: ijeong0416
    password: 340834

  jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
          default_batch_fetch_size: 100
          format_sql: false
      open-in-view: false